export const aiTools = {
  student: [
    {
      id: "homework-helper",
      name: "Homework Helper",
      description: "Get step-by-step solutions to your homework problems",
      icon: "HelpCircle",
      path: "/dashboard/homework-helper",
      color: "blue",
    },
    {
      id: "study-guide-generator",
      name: "Study Guide Generator",
      description: "Create personalized study guides for any topic",
      icon: "BookOpen",
      path: "/dashboard/study-guides",
      color: "green",
    },
    {
      id: "practice-exercises",
      name: "Practice Exercises",
      description: "Generate custom practice problems based on your skill level",
      icon: "BrainCircuit",
      path: "/dashboard/practice",
      color: "purple",
    },
    {
      id: "content-explainer",
      name: "Content Explainer",
      description: "Get clear explanations for complex topics",
      icon: "Lightbulb",
      path: "/dashboard/content-explainer",
      color: "amber",
    },
    {
      id: "ai-tutoring",
      name: "AI Tutoring",
      description: "Get personalized tutoring sessions",
      icon: "MessageSquare",
      path: "/dashboard/tutoring",
      color: "rose",
    },
  ],
  teacher: [
    {
      id: "lesson-plan-generator",
      name: "Lesson Plan Generator",
      description: "Create comprehensive lesson plans in seconds",
      icon: "Wand2",
      path: "/teacher-dashboard/tools/lesson-planner",
      color: "blue",
    },
    {
      id: "quiz-generator",
      name: "Quiz Generator",
      description: "Create customized quizzes with various question types",
      icon: "BrainCircuit",
      path: "/teacher-dashboard/tools/quiz-generator",
      color: "purple",
    },
    {
      id: "feedback-generator",
      name: "Feedback Generator",
      description: "Create personalized, constructive feedback for students",
      icon: "MessageSquare",
      path: "/teacher-dashboard/tools/feedback-generator",
      color: "green",
    },
    {
      id: "document-analyzer",
      name: "Document Analyzer",
      description: "Upload and analyze educational documents with AI",
      icon: "FileText",
      path: "/teacher-dashboard/tools/document-analyzer",
      color: "amber",
    },
  ],
  both: [
    {
      id: "speech-to-text",
      name: "Speech to Text",
      description: "Convert speech to text for accessibility and note-taking",
      icon: "Mic",
      path: "/dashboard/accessibility/speech-to-text",
      teacherPath: "/teacher-dashboard/resources/accessibility",
      color: "indigo",
    },
    {
      id: "content-explainer",
      name: "Content Explainer",
      description: "Generate clear explanations for complex topics",
      icon: "Lightbulb",
      path: "/dashboard/content-explainer",
      teacherPath: "/teacher-dashboard/tools/content-explainer",
      color: "amber",
    },
  ],
}
